### ISSUE TITLE
Add team members

### ISSUE THREAD

**Issue by singhvaibhav715** [asetalias/asetaliaslucknow.github.io#10]
Names:-
1- Lakshya 
2- Vigya Gupta
3- Umang Jain
4- Anuj Gupta

Designation: Team member For all.
Images: Keep the image tag blank.

**Comment by akshat0047** [comment]
Taking this issue!

**Comment by singhvaibhav715** [comment]
https://singhvaibhav715.github.io/asetaliaslucknow.github.io/

**Comment by singhvaibhav715** [comment]
I want to take this issue

**Comment by vips28** [comment]
@singhvaibhav715 Kindly close this issue. This issue has been rectified.
